### ISSUE TITLE
ValueError: 'rename-file' is not a valid CodeChangeAction

### ISSUE THREAD

**Issue by zhoug0x** [biobootloader/mentat#12]
getting this error when getting mentat to rename a JS file

running the repo locally on Ubuntu 22.04.2, haven't tried on any other OS

i'm not a python guy so apologies if it's an obvious env thing lol,
here's the how I recreated it along w/ the stack trace:
```
What can I do for you?
>>> rename the JS file to app.js, and update package.json with the new fil
ename                                                                     

Total token count: 1458

streaming...  use control-c to interrupt the model at any point

I will rename the JS file to app.js and update the package.json with the new filename.

Steps:
1. Rename the download-data.js file to app.js.
2. Update the package.json file with the new filename.

2023-07-26 23:48:42,828 - ERROR - an error occurred during closing of asynchronous generator <async_generator object APIRequestor.arequest.<locals>.wrap_resp at 0x7f275e2a23c0>
asyncgen: <async_generator object APIRequestor.arequest.<locals>.wrap_resp at 0x7f275e2a23c0>
Traceback (most recent call last):
  File "/home/zhoug/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 324, in wrap_resp
    yield r
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhoug/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 326, in wrap_resp
    await ctx.__aexit__(None, None, None)
  File "/usr/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
RuntimeError: anext(): asynchronous generator is already running

Total session cost: $0.00
Traceback (most recent call last):
  File "/home/zhoug/.local/bin/mentat", line 8, in <module>
    sys.exit(run_cli())
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/app.py", line 24, in run_cli
    run(paths)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/app.py", line 35, in run
    loop(paths, cost_tracker)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/app.py", line 57, in loop
    explanation, code_changes = conv.get_model_response(code_file_manager, config)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/conversation.py", line 52, in get_model_response
    state = run_async_stream_and_parse_llm_response(
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 129, in run_async_stream_and_parse_llm_response
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 158, in stream_and_parse_llm_response
    await _process_response(state, response, printer, code_file_manager)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 178, in _process_response
    _process_content_line(state, content_line, printer, code_file_manager)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 201, in _process_content_line
    state.new_line(code_file_manager)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 93, in new_line
    self.create_code_change(code_file_manager)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/parsing.py", line 71, in create_code_change
    CodeChange(json_data, self.code_lines, self.git_root, code_file_manager)
  File "/home/zhoug/.local/lib/python3.10/site-packages/mentat/code_change.py", line 50, in __init__
    self.action = CodeChangeAction(self.json_data["action"])
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'rename-file' is not a valid CodeChangeAction
```

**Comment by PCSwingle** [comment]
Hmm, it looks like the AI tried to do a 'rename-file' action (which doesn't exist). The model is supposed to output a strict json format that we read, and it just messed up. We might need to add a way for it to rename files, but for now you'll just have to rename the files yourself :smiling_face_with_tear: Other than that though, it should work fine; thanks for letting us know about this!
