### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by bhaskoro-muthohar** [biobootloader/mentat#21]
I got an error when running `mentat .`
```
app
├── * .gitignore
├── .gitlab-ci.yml
├── Dockerfile
├── README.md
├── main.py
├── helper
│   ├── __init__.py
│   ├── variables.py
├── model
│   ├── .gitignore
│   ├── clf_model.pkl
│   ├── wiki.txt.gz
│   └── word2vec,pkl
├── requirements.txt
├── sample
│   └── .gitignore
└── tests
    ├── mock_training.json
    ├── model
    │   ├── .gitignore
    │   └── wiki.txt.gz
    └── tes_training.py

Total session cost: $0.00
Traceback (most recent call last):
  File "/home/user/app/venv/bin/mentat", line 8, in <module>
    sys.exit(run_cli())
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/app.py", line 24, in run_cli
    run(paths)
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/app.py", line 35, in run
    loop(paths, cost_tracker)
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/app.py", line 48, in loop
    tokens = count_tokens(code_file_manager.get_code_message())
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/code_file_manager.py", line 260, in get_code_message
    self._read_all_file_lines()
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/code_file_manager.py", line 257, in _read_all_file_lines
    self.file_lines[abs_path] = self._read_file(abs_path)
  File "/home/user/app/venv/lib/python3.10/site-packages/mentat/code_file_manager.py", line 251, in _read_file
    lines = f.read().split("\n")
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by biobootloader** [comment]
Ah, I think Mentat thinks `wiki.txt.gz` is a code file. Right now we use `mimetypes` to determine file type, but we should check encoding to also remove things like this. Will fix soon! 

Until then, as a workaround just directly add the files you want it to edit as arguments, instead of the whole directory.
