### ISSUE TITLE
Install fails while following set up video: ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.

### ISSUE THREAD

**Issue by Gillinghammer** [biobootloader/mentat#34]
```
Traceback (most recent call last):
  File "/Users/.../.pyenv/versions/3.11.0/bin/mentat", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/mentat/app.py", line 24, in run_cli
    run(paths)
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/mentat/app.py", line 35, in run
    loop(paths, cost_tracker)
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/mentat/app.py", line 48, in loop
    tokens = count_tokens(code_file_manager.get_code_message())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/mentat/llm_api.py", line 57, in count_tokens
    return len(tiktoken.encoding_for_model("gpt-4").encode(message))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/tiktoken/core.py", line 117, in encode
    raise_disallowed_special_token(match.group())
  File "/Users/.../.pyenv/versions/3.11.0/lib/python3.11/site-packages/tiktoken/core.py", line 351, in raise_disallowed_special_token
    raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.
```

**Comment by biobootloader** [comment]
I guess the files you were running it on contained `<|endoftext|>` somewhere? It seems we need to update our `tiktoken` call to encode special tokens as normal text - all we are using it for is counting tokens so this shouldn't cause issues

**Comment by Bbasche** [comment]
I don't see <|endoftext|> in any of my files?

**Comment by biobootloader** [comment]
> I don't see <|endoftext|> in any of my files

huh, this is confusing. If it's possible could you figure out the type of file that's causing this for you? i.e. run with different subsets of your files to see which ones cause it?

**Comment by Gillinghammer** [comment]
Im personally just following your video tutorial line for line and getting
this. It’s an empty new_project git initialized directory. Nothing special.

**Comment by biobootloader** [comment]
I wasn't able to replicate this crash myself, but I've just pushed a fix: https://github.com/biobootloader/mentat/pull/39

That PR is merged and I put new code on PYPI. If one of you could test if it solved it for you that'd be great!

**Comment by Gillinghammer** [comment]
I think we're in business, got the official prompt `What can I do for you?`
